# Generated by Django 5.2.11 on 2026-03-10 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant to Manager"),
                    ("manager", "Manager to Landlord"),
                ],
                default="tenant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
